services:
  - docker

install:
  - git clone https://github.com/harvestcore/ipcontainer
  - docker pull harvestcore/ipcontainer-test-mysql
  - docker pull harvestcore/ipcontainer-test-python
  - docker images
script: 
  - docker run -d harvestcore/ipcontainer-test-mysql:ipctmysql && docker run -d harvestcore/ipcontainer-test-python:ipctpython
