services:
  - docker

install:
  - git clone https://github.com/harvestcore/ipcontainer-test
  - git clone https://github.com/harvestcore/IPContainer
  - cp ipcontainer-test/config.json IPContainer/src/
  - cp -r IPContainer ipcontainer-test/python
  - docker pull harvestcore/ipcontainer-test-mysql:ipctmysql
  - docker build -t pytestpython:ipctpython ./ipcontainer-test/python
script: 
  - docker run -d harvestcore/ipcontainer-test-mysql:ipctmysql
  - docker ps
  - docker images
  - sleep 20
  - docker run pytestpython:ipctpython cd ./IPContainer && pytest
